### ISSUE TITLE
TransferTransaction to alias does not work

### ISSUE THREAD

**Issue by kireevvd** [wavesplatform/waves-transactions#19]
Hello!
In this library, written that in a TransferTransaction 'recipient' property is a string.
In testnet.ide.wavesplatform.com I create a transaction to the alias "init@vecr":
**const transferTxToAlias = transfer({recipient: "init@vecr", amount: 500000, assetId: null}, mySeed)**
In this case i get an error: "There is no character "@" in the Base58 sequence!"

If i convert "init@vecr" to Base58 and input it in 'recipient' field:
**const transferTxToAlias = transfer({recipient: "2LqVohyv5tZoo", amount: 500000, assetId: null}, mySeed)**
I get an error: "Address invalid"

I make some mistake or console in IDE does not work with 'alias' in 'recipient' property? 
If console in IDE doesn't work with 'alias' in 'recipient' property, can you fix this problem, please.
Thaks in advance!

**Comment by siemarell** [comment]
Hi! thanks for report. This library indeed has problem with alias

**Comment by siemarell** [comment]
Version 3.6.0 now accepts aliases. You should write alias like this: `alias:{chainId}:{alias}`. In your example it should be `alias:T:init@vect`. IDE will be updated next week

**Comment by kireevvd** [comment]
Thank you!
