### ISSUE TITLE
seed dictionary is wrong size and contains duplicate words 

### ISSUE THREAD

**Issue by alxarch** [wavesplatform/waves-transactions#20]
Probably some formatting of the file at some point got messed up.
https://github.com/wavesplatform/waves-transactions/blob/81b36b0375638114db43385f8cc61bde34bfcd33/src/seedUtils/dictionary.ts#L134
I don't know if this has security implications over a seed phrase's entropy

**Comment by siemarell** [comment]
Thanks for report. It doesn't matter since dictionary is stored as javascript array
