### ISSUE TITLE
sell/buy order creation error

### ISSUE THREAD

**Issue by sultana-mnw** [wavesplatform/waves-transactions#39]
Hi waves Team, 

Am getting Error while creating buy/selll orders using @waves-transactions.

Code: 
`   const signedTranserTx = order({ 
        amount:200000000,
        price: 0.001,
        priceAsset: "DWgwcZTMhSvnyYCoWLRUXXSH1RSkzThXLJhww9gwkqdn",
        matcherPublicKey: "7kPFrHDiGw1rCm7LPszuECwWYL3dMf6iMifLRDJQZMzy",
        orderType: "buy",
        }, seed)
       console.log(signedTranserTx)
        broadcast(signedTranserTx, nodeUrl).then(resp => console.log(resp))
`

**Error:**

`Error: Incorrect tx type: undefined
    at Object.getTransactionSchema (/home/devel-sultana/Desktop/wb/node_modules/@waves/marshall/dist/schemas.js:523:15)
    at Object.stringifyTx (/home/devel-sultana/Desktop/wb/node_modules/@waves/marshall/dist/jsonMethods.js:166:30)
    at broadcast (/home/devel-sultana/Desktop/wb/node_modules/@waves/waves-transactions/dist/nodeInteraction.js:220:75)
    at sell (/home/devel-sultana/Desktop/wb/a.js:92:7)
    at Object.<anonymous> (/home/devel-sultana/Desktop/wb/a.js:97:7)
`

is that am doing right. please give possible solution for that.

Thanks

**Comment by siemarell** [comment]
Hi! You are trying to send order to waves node, but you should send it to matcher instead. Use `submitOrder` function

**Comment by sultana-mnw** [comment]
while using submitOrder function for sending orders am getting this error.

{ Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)
  code: 'CERT_HAS_EXPIRED',
  config:
   { url: 'https://matcher.testnet.wavesnodes.com/matcher/orderbook',
     method: 'post',
     data:
      '{"orderType":"sell","version":2,"assetPair":{"amountAsset":null,"priceAsset":"DWgwcZTMhSvnyYCoWLRUXXSH1RSkzThXLJhww9gwkqdn"},"price":361,"amount":120000000,"timestamp":1569220762661,"expiration":1571726362661,"matcherFee":300000,"matcherPublicKey":"8QUAqtTckM5B8gvcuP7mMswat9SjKUuafJMusEoSn1Gy","senderPublicKey":"Gqexhd3H6RDBFQY9GcQdEPkxjzkiT9bAvrHXqJzJTaCg","proofs":["3joX6S6QSfuJ9Kh6STjb7bHtKd9wpP4s9GUm2cbomanWUKWeWMsgUwoDwaimHviRSkTvtP9M42RaPFMrQfQTLJy1"],"id":"9YAqt2m8YhiuD9S28hm2cNHHdv3WtM8mFMBTNR5V7bNf"}',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        'User-Agent': 'axios/0.19.0',
        'Content-Length': 514 },

**Comment by siemarell** [comment]
Something is wrong with matcher SSL certificate. Problem is not related to library. You can try opening [this](https://matcher.testnet.wavesnodes.com/matcher/orderbook) url in your browser. I think it will be fixed soon

**Comment by siemarell** [comment]
You can use https://nodes-testnet.wavesnodes.com. This host has valid SSL cert

**Comment by siemarell** [comment]
Certificate for https://matcher.testnet.wavesnodes.com has been fixed

**Comment by sultana-mnw** [comment]
Its works fine now thank you.
