### ISSUE TITLE
How to use this lib in testnet

### ISSUE THREAD

**Issue by fabiomattes2016** [wavesplatform/waves-transactions#9]
I need to do some transaction testing using javascript and would like to know how I use it in testnet.

Tnx a lot!

**Comment by siemarell** [comment]
You need two things.
1. Some transactions have chainId as param. You need to pass 'T'. E.g:
 ```javascript
const burnTx = burn({assetId:'someId', amount:1000, chainId:'T'})
```
2. You send tx to testnet node. E.g: 
```javascript
await broadcast(burnTx, ' https://testnodes.wavesnodes.com')
```

**Comment by siemarell** [comment]
I close this issue as incative
